version: "3.8"

services:
  app:
    env_file:
      - src/.env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: IPSA_AI
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
